---
plugin: hive_services
services:
  nginx:
    image:
      from: nginx
      roles:
        - python-aptk
        - nginx-init
    ports:
      - 8080:80
    volumes:
      - source: nginx_conf
        target: /etc/nginx/conf.d
        type: volume
        drbd:
          fstype: xfs
          size: 500M
  db:
    image: mariadb:10.6
    command:
      - "--transaction-isolation=READ-COMMITTED"
      - "--log-bin=binlog"
      - "--binlog-format=ROW"
    environment:
      - MYSQL_ROOT_PASSWORD=mariadbXXX
      - MYSQL_PASSWORD=nextcloudXXX
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    volumes:
      - source: mysql_data
        target: /var/lib/mysql
        type: volume
        drbd:
          fstype: xfs
          size: 3G
    backup_scripts:
      - name: nextcloud-db
        backup_command: mysqldump -u root -pexample redmine > /root/today.sql
        restore_command: mysql -u root -pexample redmine < /root/today.sql
        backup_file: /root/today.sql
        restore_file: /root/today.sql
        ext: sql
        cleanup_days_before: 3
  nextcloud:
    image: nextcloud
    restart_config:
      condition: "on-failure"
      delay: 5s
    volumes:
      - source: nextcloud
        target: /var/www/html
        type: volume
        drbd:
          fstype: xfs
          size: 1G
    environment:
      - MYSQL_PASSWORD=nextcloudXXX
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db